apps/rsvp_web/lib/rsvp_web/router.ex
defmodule RsvpWeb.Router do
  use RsvpWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  # pipeline :authorized do
  #   plug :browser
  #   plug RsvpWeb.AuthorizedPlug
  # end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", RsvpWeb do
    pipe_through :browser

    get "/", PageController, :index


    get "/login", LoginController, :index
    post "/login", LoginController, :login
  end

  scope "/events", RsvpWeb do
    pipe_through :browser

    get "/", EventController, :list
    get "/new", EventController, :create
    post "/new", EventController, :add
    get "/:id", EventController, :show
    post "/:id/reserve", EventController, :reserve
  end

  # Other scopes may use custom stacks.
  # scope "/api", RsvpWeb do
  #   pipe_through :api
  # end
end

apps/rsvp_web/lib/rsvp_web/controllers/event_controller.ex
defmodule RsvpWeb.EventController do
  use RsvpWeb, :controller

  # plug RsvpWeb.AuthorizedPlug when action in [:create]
  plug RsvpWeb.AuthorizedPlug, "create" when action in [:create]

  def show(conn, %{"id" => id}) do
    event =
    Rsvp.EventQueries.get_by_id(id)
    |> IO.inspect()
    render( conn, "details.html", event: event)
  end

  def list(conn, _params) do
    events = Rsvp.EventQueries.get_all()
    render(conn, "list.html", events: events)
  end

  def create(conn, %{error: %Ecto.Changeset{} = errors}) do
    # IO.puts("errors")
    # IO.inspect(errors)
    # errors = %{errors | date: nil}
    IO.inspect(errors.data)
    render(conn, "create.html", changeset: errors)
  end

  def create(conn, _params) do
    changeset = Rsvp.Events.changeset(%Rsvp.Events{}, %{})
    render(conn, "create.html", changeset: changeset)
  end

  def add(conn, %{"events" => events}) do


    changeset =  Rsvp.Events.changeset(%Rsvp.Events{}, events)
    # IO.inspect(changeset)

    case Rsvp.EventQueries.create(changeset) do
      {:ok, %{id: id}} -> redirect(conn, to: Routes.event_path(conn, :show, id))
      {:error, reasons} ->
        IO.inspect(reasons)
        create(conn, %{error: reasons})
    end
  end

  def reserve(conn, %{"reservation" => %{"quantity" => quantity}, "id" => id}) do
    event_tuple = Rsvp.EventQueries.decrease_quantity(id, quantity)
    RsvpWeb.EventChannel.send_update(event_tuple)
    redirect(conn, to: Routes.event_path(conn, :show, id))
  end
end

apps/rsvp_web/lib/rsvp_web/controllers/login_controller.ex
defmodule RsvpWeb.LoginController do
  use RsvpWeb, :controller


  def index(conn, _params) do
    render(conn, "login.html")
  end

  def login(conn, %{"login" => %{"username" => username}}) do
    expiration = 60 * 60 * 24 * 7
    conn = Plug.Conn.assign(conn, :current_user, username)

    conn
    |> Plug.Conn.put_resp_cookie("username", username, max_age: expiration)
    |> redirect(  to: Routes.page_path(conn, :index))
  end
end

apps/rsvp_web/lib/rsvp_web/controllers/page_controller.ex
defmodule RsvpWeb.PageController do
  use RsvpWeb, :controller

  def index(conn, _params) do
    render(conn, "index.html")
  end
end

apps/rsvp_web/lib/rsvp_web/views/error_view.ex
defmodule RsvpWeb.ErrorView do
  use RsvpWeb, :view

  # If you want to customize a particular status code
  # for a certain format, you may uncomment below.
  # def render("500.html", _assigns) do
  #   "Internal Server Error"
  # end

  # By default, Phoenix returns the status message from
  # the template name. For example, "404.html" becomes
  # "Not Found".
  def template_not_found(template, _assigns) do
    Phoenix.Controller.status_message_from_template(template)
  end
end

apps/rsvp_web/lib/rsvp_web/views/event_view.ex
defmodule RsvpWeb.EventView do
  use RsvpWeb, :view

  def format_date(date) do
    %{year: year, day: day, month: month} = date
    "#{year}/#{pad(month)}/#{pad(day)}"
  end

  def format_time(date) do
    %{hour: hour, minute: minute, second: second} = date;
    hour = pad(hour)
    minute = pad(minute)
    second = pad(second)
    "#{hour}:#{minute}:#{second}"
  end

  defp pad(string) do
    String.pad_leading(inspect(string), 2, "0")
  end
end

apps/rsvp_web/lib/rsvp_web/views/layout_view.ex
defmodule RsvpWeb.LayoutView do
  use RsvpWeb, :view

  def log_conn(conn), do: IO.inspect(conn)

  def format_username(username) do
    first_char =
      String.at(username, 0)
      |> String.upcase()
    first_char <> String.slice(username, 1, String.length(username))
  end
end

apps/rsvp_web/lib/rsvp_web/views/login_view.ex
defmodule RsvpWeb.LoginView do
  use RsvpWeb, :view
end

apps/rsvp_web/lib/rsvp_web/views/page_view.ex
defmodule RsvpWeb.PageView do
  use RsvpWeb, :view
end

apps/rsvp_web/lib/rsvp_web/views/shared_view.ex
defmodule RsvpWeb.SharedView do
  use RsvpWeb, :view
end

apps/rsvp_web/lib/rsvp_web/templates/event/create.html.eex
<h1>Add Event</h1>
<%= form_for @changeset, Routes.event_path(@conn, :add), fn f -> %>
<div class="form-group">
  <%= label f, :title, "Title" %>
  <%= text_input f, :title, class: "form-control" %>
  <%= error_tag f, :title %>
</div>

<div class="form-group">
  <%= label f, :location, "Location" %>
  <%= text_input f, :location, class: "form-control" %>
  <%= error_tag f, :location %>
</div>

<div class="form-group">
  <%= label f, :date, "Date" %>
  <%= datetime_local_input f, :date, class: "form-control" %>
  <%= error_tag f, :date %>
</div>

<div class="form-group">
  <%= label f, :quantity_available, "Total Reservations" %>
  <%= number_input f, :quantity_available  %>
  <%= error_tag f, :quantity_available %>
</div>

<div class="form-group">
  <%= label f, :description, "Description"%>
  <%= textarea f, :description, class: "form-control", rows: 5 %>

</div>
<div class="form-group">
  <%= submit "Add" %>
</div>
<% end %>

apps/rsvp_web/lib/rsvp_web/templates/event/details.html.eex
<h1 class="event-title">
<%= @event.title %>,
</h1>
<h1> <small> <%= @event.location %></small></h1>
<h3><span><%= format_date(@event.date) %></span> at <span class="time-text"><%= format_time(@event.date) %></span></h3>
<p><%= @event.description %></p>
<h4>Available Spots: 
  <span class="quantity"><%= @event.quantity_available %></span>
</h4>

<%= form_for @conn, Routes.event_path(@conn, :reserve, @event.id), [as: :reservation], fn f -> %>
  <div class="form-group">
    <%= label f, :quantity, "Quantity" %>
    <%= number_input f, :quantity, class: "form-control", min: 1 %>
  </div>


  <div class="form-group">
    <%= submit "Reserve" %>
  </div>
<% end %>

<span id="id" data-id="<%= @event.id %>"></span>

apps/rsvp_web/lib/rsvp_web/templates/event/list.html.eex
<div class="list">
  <div>
    <h1>All Events </h1>
    <%= render(RsvpWeb.SharedView, "add-event.html", conn: @conn, class: ["right", "top"]) %>
    <%= render(RsvpWeb.SharedView, "count.html", list: @events) %>
  </div>
  <div class="list-group">
    <%= for event <- @events do %>
      <%= render("summary.html", event: event, conn: @conn) %>
    <% end %>
  </div>
</div>

apps/rsvp_web/lib/rsvp_web/templates/event/summary.html.eex
<!-- <a href="events/<%= @event.id %>"> -->
<div class="summary">
  <a href="<%= Routes.event_path(@conn, :show, @event.id) %>">
    <div class="list-group-item">
      <h4 class="list-group-item-heading"><%= @event.title %></h4>
      <span>
        <span class="text-muted"><%= @event.location %></span>
        <span class="pull-right">
          <strong>
          <%= format_date(@event.date) %>
          </strong>
        </span>
      </span>
    </div>    
  </a>
</div>

apps/rsvp_web/lib/rsvp_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Rsvp</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
  </head>
  <body>
    <header>
      <section class="container">
        <div class="brand">
          <%= link "RSVP", to: Routes.page_path(@conn, :index) %>
        </div>
        <nav role="navigation">
          <ul class="nav">
            <li><a href="<%= Routes.event_path(@conn, :list) %>">All Events</a></li>
          </ul>
          <ul class="nav right">
            <li>
              <%= if @conn.cookies["username"] do %>
                <%= format_username(@conn.cookies["username"]) %>
              <% else %>
                <li>
                  <%= link "Login", to: Routes.login_path(@conn, :index) %>
                </li>
              <% end %>
            </li>
          </ul>
        </nav>
      </section>
    </header>
    <main role="main" class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= render @view_module, @view_template, assigns %>
    </main>
    <script type="text/javascript" src='<%= Routes.static_path(@conn, "/js/app.js") %>'></script>
  </body>
</html>

apps/rsvp_web/lib/rsvp_web/templates/login/login.html.eex
<h1>Login Here</h1>
<%= form_for @conn, Routes.login_path(@conn, :login), [as: :login], fn f -> %>

  <div class="form-group">
    <%= label f, :username, "Username" %>
    <%= text_input f, :username, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= label f, :password, "Password" %>
    <%= password_input f, :password, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= submit "Login" %>
  </div>

<% end %>

apps/rsvp_web/lib/rsvp_web/templates/page/index.html.eex
<section class="phx-hero">
  <h1><%= gettext "Welcome to %{name}!", name: "RSVP" %></h1>
  <p>Save all your events and get reminders ahead of time!!!</p>
    <div class="padding">
      <%= render(RsvpWeb.SharedView, "add-event.html", conn: @conn, class: []) %>
    </div>
</section>

<section class="row">
  <article class="column">
  </article>
  <article class="column">
  </article>
</section>

apps/rsvp_web/lib/rsvp_web/templates/shared/add-event.html.eex
<%= link "Add Event", to: Routes.event_path(@conn, :create), type: "button", class: Enum.join(["fab" | @class], " ") %>

apps/rsvp_web/lib/rsvp_web/templates/shared/count.html.eex
<h3>Total Count <%= Enum.count(@list) %></h3>